export const DEFAULT_SYNC_PORT = 3456;
export const DEFAULT_WS_PORT = 3457;
export const DEFAULT_BACKUP_DIR = "/opt/vaultkeeper/backups";
export const DEFAULT_DATA_DIR = "/opt/vaultkeeper/data";
export const SYNC_PROTOCOL_VERSION = 1;
export const MAX_FILE_SIZE = 50 * 1024 * 1024; // 50MB
export const MAX_ATTACHMENT_SIZE = 25 * 1024 * 1024; // 25MB
export const SYNC_INTERVAL_MS = 30000;
export const INDEX_CHUNK_SIZE = 100;
export const GRAPH_MAX_NODES = 5000;
export const GRAPH_MAX_EDGES = 20000;
export const VAULT_VERSION = 1;
export const SUPPORTED_IMAGE_EXTENSIONS = [".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"];
export const SUPPORTED_ATTACHMENT_EXTENSIONS = [".pdf", ".mp4", ".webm", ".mp3", ".wav", ".ogg", ".zip"];
export const NOTE_EXTENSIONS = [".md", ".markdown"];
export const BACKLINK_PATTERN = /\[\[([^\]]+)\]\]/g;
export const TAG_PATTERN = /#([\w-]+)/g;
export const FRONTMATTER_PATTERN = /^---\n([\s\S]*?)\n---/;
